fail_fast: false
files: '.*\.(c|h)pp$'
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=Microsoft", "-i"]
      - id: clang-tidy
        # without this arg, it treats *.h files as C headers
        args: ["--extra-arg-before=-xc++"]
      # - id: oclint
      # - id: uncrustify
      # - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use
