name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: switch to gcc-11 on linux
      if: matrix.configurations.os == "ubuntu-latest"
      run: |
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11

    - name: Install dependencies
      run: sudo apt install build-essential libfmt-dev
      
    - name: Build executable
      run: make
      
    - name: Run tests
      run: make unit_test
